name: build1

on:
  workflow_dispatch:
    inputs:
      workflow_identifier:
        description: 'Identifier for this workflow run'
        required: true
      sleep_duration:
        description: 'Duration to sleep in seconds'
        required: false
        default: '20'

jobs:
  build1:
    runs-on: [self-hosted, ManagedDevOps.Pool=tt-pool3, "JobId=build1-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}"]

    steps:
      - uses: actions/checkout@v4

      - name: Do Build
        run: |
          echo "Fake build step"
          sleep ${{ github.event.inputs.sleep_duration }}
          echo "Build step complete"


