name: basic - workflow

on:
  workflow_dispatch:
    inputs:
      workflow_identifier:
        description: 'Identifier for this workflow run'
        required: true

jobs:
  build1:
    runs-on: [self-hosted, ManagedDevOps.Pool=tt-pool3]

    steps:
      - uses: actions/checkout@v4

      - name: Do Build
        run: |
          echo "Fake build step"
          sleep 20
          echo "Build step complete"


